'use client'
import { FormEvent, useState } from 'react'
import { createBrowserClient } from '@supabase/ssr'

export default function AdminLoginPage() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');const supabase=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError('Email ou mot de passe incorrect.');setLoading(false);return}window.location.href='/admin'}
  return <main style={{minHeight:'100dvh',display:'grid',placeItems:'center',padding:24,background:'linear-gradient(135deg,#fff7f2,#eef4ff)'}}><div style={{width:'100%',maxWidth:440,background:'#fff',border:'1px solid #e7e8ee',borderRadius:28,padding:34,boxShadow:'0 25px 70px rgba(20,30,50,.12)'}}><div style={{fontWeight:950,fontSize:30,letterSpacing:'-.07em'}}>AUTO<span style={{color:'#e1042c'}}>+</span></div><p style={{fontSize:11,fontWeight:900,letterSpacing:'.16em',color:'#e1042c'}}>PRIVATE ADMIN</p><h1 style={{fontSize:38,letterSpacing:'-.05em',margin:'12px 0'}}>Control Center</h1><p style={{color:'#626979',lineHeight:1.6}}>Analytics, clics produits et performances Auto+.</p><form onSubmit={submit} style={{display:'grid',gap:16,marginTop:28}}><label style={{fontWeight:800,fontSize:13}}>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required autoComplete="email" style={{display:'block',width:'100%',marginTop:7,padding:13,border:'1px solid #dfe2ea',borderRadius:12}}/></label><label style={{fontWeight:800,fontSize:13}}>Mot de passe<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required autoComplete="current-password" style={{display:'block',width:'100%',marginTop:7,padding:13,border:'1px solid #dfe2ea',borderRadius:12}}/></label>{error&&<p style={{color:'#c40027',fontSize:13,fontWeight:700}}>{error}</p>}<button disabled={loading} style={{padding:14,border:0,borderRadius:12,background:'#12141a',color:'#fff',fontWeight:900,cursor:'pointer'}}>{loading?'Connexion…':'Accéder au dashboard →'}</button></form></div></main>
}
