-- Auto+ analytics + admin security
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event text not null check (event in ('product_view','affiliate_click')),
  product_id text not null,
  slug text not null,
  name text,
  category text,
  referrer text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_slug_idx on public.analytics_events(slug);
create index if not exists analytics_events_event_idx on public.analytics_events(event);
create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);

alter table public.analytics_events enable row level security;

-- No public SELECT/UPDATE/DELETE policies.
-- Server routes use the service-role key.
